[package]
name = "lang"
version = "0.1.0"
authors = ["Krishna Ramasimha <krishnaramasimha12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs = "0.0.5"
io = "0.0.2"
logos = "0.12.0"
